// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import path from 'node:path'
import { defineConfig } from 'prisma/config'

const configuredUrl = process.env['DATABASE_URL']

if (!configuredUrl) {
  throw new Error('DATABASE_URL chưa được cấu hình.')
}

const prismaRoot = path.resolve(process.cwd(), 'backend', 'prisma')

const datasourceUrl = configuredUrl.startsWith('file:./')
  ? `file:${path.resolve(prismaRoot, configuredUrl.slice(7)).replaceAll('\\', '/')}`
  : configuredUrl

export default defineConfig({
  schema: 'backend/prisma/schema.prisma',
  migrations: {
    path: 'backend/prisma/migrations',
    seed: 'tsx backend/prisma/seed.ts',
  },
  datasource: {
    url: datasourceUrl,
  },
})
